name: Deploy to EKS and Docker Images

on:
  workflow_dispatch:  # Triggered manually

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Configure AWS 
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    # Checkout the repository to get access to the code
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Set up Docker Buildx (required for multi-platform support)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: us-east-1

    - name: Docker login to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 677276078111.dkr.ecr.us-east-1.amazonaws.com
    # Build Docker images for the patient service and appointment service
    - name: Build Appointment Service Docker Image
      run: |
        cd ./app/appointment-service/
        docker build -t appointment-image:latest .
        docker tag appointment-image:latest 677276078111.dkr.ecr.us-east-1.amazonaws.com/eks-repo-appointment:latest
    
    - name: Build Patient Service Docker Image
      run: |
        cd ./app/patient-service/
        docker build -t patient-image:latest .
        docker tag patient-image:latest 677276078111.dkr.ecr.us-east-1.amazonaws.com/eks-repo-patient:latest
    
    # Push Docker images to ECR
    - name: Push Appointment Service Image to ECR
      run: |
        docker push 677276078111.dkr.ecr.us-east-1.amazonaws.com/eks-repo-appointment:latest

    - name: Push Patient Service Image to ECR
      run: |
        docker push 677276078111.dkr.ecr.us-east-1.amazonaws.com/eks-repo-patient:latest

    # Install kubectl to interact with the Kubernetes cluster
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Set up EKS kubeconfig
      run: aws eks --region us-east-1 update-kubeconfig --name my-eks-cluster

    # Apply Kubernetes YAML configurations
    - name: Apply Kubernetes Configuration Files
      run: |
        cd ./app/k8s/
        kubectl apply -f appointment-service-deployment.yaml
        kubectl apply -f appointment-service-service.yaml
        kubectl apply -f patient-service-deployment.yaml
        kubectl apply -f patient-service-service.yaml
    
    # Sleep for a minute so that pods get started
    - name: Sleep for 60 seconds
      run: sleep 60


    # Run kubectl commands to verify deployment and services
    - name: Verify the Deployment and Services
      run: |
        kubectl get pods
        kubectl get services
