name: Destroy AWS Infrastructure with Terraform IAC.

on:
  workflow_dispatch: 
    inputs:
      environment:
        description: "Choose the environment to Destroy (Dev, Staging, Prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  destroy-infra:
    name: Destroy Terraform Resources
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      WORKING_DIR: ./infra/environment/${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Terraform Init
        run: |
          cd ${{ env.WORKING_DIR }}
          terraform init

      - name: Destroy Resources
        run: |
          cd ${{ env.WORKING_DIR }}
          terraform destroy -auto-approve
