name: Provisong Prometheus and Grafana using Helm Charts.
run-name: infra prov
on:
  workflow_dispatch:
       

jobs:
  terraform:
    name: Terraform-infra
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

    

      # Step: Terraform Init
      - name: Terraform Init
        run: | 
          cd ./monitoring/
          terraform init

  
      # Step: Terraform Plan
      - name: Terraform Plan
        run: |
          cd ./monitoring/
          terraform plan 

     
      # Step: Apply Terraform 
      - name: Apply Terraform configuration
        run: |
          cd ./monitoring/
          terraform apply -auto-approve
